Revert "time: move frequently used functions to headers and declare them inline"
In file included from ../include/linux/sched.h:17,
                 from ../arch/arm64/kernel/asm-offsets.c:21:
../include/linux/jiffies.h: In function 'jiffies_to_msecs':
../include/linux/jiffies.h:301:26: error: 'HZ_TO_MSEC_NUM' undeclared (first use in this function)
  301 |  return DIV_ROUND_UP(j * HZ_TO_MSEC_NUM, HZ_TO_MSEC_DEN);
      |                          ^~~~~~~~~~~~~~
../include/linux/kernel.h:67:30: note: in definition of macro 'DIV_ROUND_UP'
   67 | #define DIV_ROUND_UP(n,d) (((n) + (d) - 1) / (d))
      |                              ^
../include/linux/jiffies.h:301:26: note: each undeclared identifier is reported only once for each function it appears in
  301 |  return DIV_ROUND_UP(j * HZ_TO_MSEC_NUM, HZ_TO_MSEC_DEN);
      |                          ^~~~~~~~~~~~~~
../include/linux/kernel.h:67:30: note: in definition of macro 'DIV_ROUND_UP'
   67 | #define DIV_ROUND_UP(n,d) (((n) + (d) - 1) / (d))
      |                              ^
../include/linux/jiffies.h:301:42: error: 'HZ_TO_MSEC_DEN' undeclared (first use in this function)
  301 |  return DIV_ROUND_UP(j * HZ_TO_MSEC_NUM, HZ_TO_MSEC_DEN);
      |                                          ^~~~~~~~~~~~~~
../include/linux/kernel.h:67:36: note: in definition of macro 'DIV_ROUND_UP'
   67 | #define DIV_ROUND_UP(n,d) (((n) + (d) - 1) / (d))
      |                                    ^
In file included from ../include/linux/sched.h:20,
                 from ../arch/arm64/kernel/asm-offsets.c:21:
../include/linux/jiffies.h: In function 'jiffies_to_usecs':
../include/linux/jiffies.h:316:14: error: 'HZ_TO_USEC_NUM' undeclared (first use in this function)
  316 |  return (j * HZ_TO_USEC_NUM) / HZ_TO_USEC_DEN;
      |              ^~~~~~~~~~~~~~
../include/linux/jiffies.h:316:32: error: 'HZ_TO_USEC_DEN' undeclared (first use in this function)
  316 |  return (j * HZ_TO_USEC_NUM) / HZ_TO_USEC_DEN;
      |                                ^~~~~~~~~~~~~~
../include/linux/jiffies.h: In function 'msecs_to_jiffies':
../include/linux/jiffies.h:376:10: error: 'MSEC_TO_HZ_MUL32' undeclared (first use in this function)
  376 |  return (MSEC_TO_HZ_MUL32 * m + MSEC_TO_HZ_ADJ32)
      |          ^~~~~~~~~~~~~~~~
../include/linux/jiffies.h:376:33: error: 'MSEC_TO_HZ_ADJ32' undeclared (first use in this function)
  376 |  return (MSEC_TO_HZ_MUL32 * m + MSEC_TO_HZ_ADJ32)
      |                                 ^~~~~~~~~~~~~~~~
../include/linux/jiffies.h:377:6: error: 'MSEC_TO_HZ_SHR32' undeclared (first use in this function)
  377 |   >> MSEC_TO_HZ_SHR32;
      |      ^~~~~~~~~~~~~~~~
../include/linux/jiffies.h: In function 'usecs_to_jiffies':
../include/linux/jiffies.h:390:10: error: 'USEC_TO_HZ_MUL32' undeclared (first use in this function)
  390 |  return (USEC_TO_HZ_MUL32 * u + USEC_TO_HZ_ADJ32)
      |          ^~~~~~~~~~~~~~~~
../include/linux/jiffies.h:390:33: error: 'USEC_TO_HZ_ADJ32'

This reverts commit d33dcbc9923f2a141806a197ba118559317f842e.